ALTER TABLE task_events ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE task_events ADD COLUMN IF NOT EXISTS schema_version TEXT NOT NULL DEFAULT '';
ALTER TABLE task_events ADD COLUMN IF NOT EXISTS event_name TEXT NOT NULL DEFAULT '';
