# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from synapse.v1 import agent_pb2 as synapse_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeStub(object):
    """运行时服务：提供健康检查、任务流式执行与长期记忆管理。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/synapse.v1.AgentRuntime/Health',
                request_serializer=synapse_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_stream(
                '/synapse.v1.AgentRuntime/SubmitTask',
                request_serializer=synapse_dot_v1_dot_agent__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.MemoryWrite = channel.unary_unary(
                '/synapse.v1.AgentRuntime/MemoryWrite',
                request_serializer=synapse_dot_v1_dot_agent__pb2.MemoryWriteRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryWriteResponse.FromString,
                _registered_method=True)
        self.MemoryRecall = channel.unary_unary(
                '/synapse.v1.AgentRuntime/MemoryRecall',
                request_serializer=synapse_dot_v1_dot_agent__pb2.MemoryRecallRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryRecallResponse.FromString,
                _registered_method=True)
        self.MemoryDelete = channel.unary_unary(
                '/synapse.v1.AgentRuntime/MemoryDelete',
                request_serializer=synapse_dot_v1_dot_agent__pb2.MemoryDeleteRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryDeleteResponse.FromString,
                _registered_method=True)
        self.MemoryList = channel.unary_unary(
                '/synapse.v1.AgentRuntime/MemoryList',
                request_serializer=synapse_dot_v1_dot_agent__pb2.MemoryListRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryListResponse.FromString,
                _registered_method=True)
        self.GetToolPolicy = channel.unary_unary(
                '/synapse.v1.AgentRuntime/GetToolPolicy',
                request_serializer=synapse_dot_v1_dot_agent__pb2.GetToolPolicyRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.GetToolPolicyResponse.FromString,
                _registered_method=True)
        self.ApplyToolPolicy = channel.unary_unary(
                '/synapse.v1.AgentRuntime/ApplyToolPolicy',
                request_serializer=synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/synapse.v1.AgentRuntime/ListTools',
                request_serializer=synapse_dot_v1_dot_agent__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_agent__pb2.ListToolsResponse.FromString,
                _registered_method=True)


class AgentRuntimeServicer(object):
    """运行时服务：提供健康检查、任务流式执行与长期记忆管理。
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryRecall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyToolPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.HealthRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.HealthResponse.SerializeToString,
            ),
            'SubmitTask': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.SubmitTaskRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.AgentEvent.SerializeToString,
            ),
            'MemoryWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryWrite,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryWriteRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.MemoryWriteResponse.SerializeToString,
            ),
            'MemoryRecall': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryRecall,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryRecallRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.MemoryRecallResponse.SerializeToString,
            ),
            'MemoryDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryDelete,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryDeleteRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.MemoryDeleteResponse.SerializeToString,
            ),
            'MemoryList': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryList,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.MemoryListRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.MemoryListResponse.SerializeToString,
            ),
            'GetToolPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolPolicy,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.GetToolPolicyRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.GetToolPolicyResponse.SerializeToString,
            ),
            'ApplyToolPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyToolPolicy,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=synapse_dot_v1_dot_agent__pb2.ListToolsRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_agent__pb2.ListToolsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.v1.AgentRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.v1.AgentRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntime(object):
    """运行时服务：提供健康检查、任务流式执行与长期记忆管理。
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/Health',
            synapse_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/synapse.v1.AgentRuntime/SubmitTask',
            synapse_dot_v1_dot_agent__pb2.SubmitTaskRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/MemoryWrite',
            synapse_dot_v1_dot_agent__pb2.MemoryWriteRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.MemoryWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryRecall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/MemoryRecall',
            synapse_dot_v1_dot_agent__pb2.MemoryRecallRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.MemoryRecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/MemoryDelete',
            synapse_dot_v1_dot_agent__pb2.MemoryDeleteRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.MemoryDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/MemoryList',
            synapse_dot_v1_dot_agent__pb2.MemoryListRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.MemoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetToolPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/GetToolPolicy',
            synapse_dot_v1_dot_agent__pb2.GetToolPolicyRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.GetToolPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyToolPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/ApplyToolPolicy',
            synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.ApplyToolPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.AgentRuntime/ListTools',
            synapse_dot_v1_dot_agent__pb2.ListToolsRequest.SerializeToString,
            synapse_dot_v1_dot_agent__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
